#!/usr/bin/env python

import os

from zoonibot.bot import ZooniBot
from zoonibot.responses import zoonibot_response
from zoonibot.finders import find_zoonibot_tag

def main():
    try:
        username = os.environ["ZOONAME"]
        api_key = os.environ["ZOOKEY"]
    except KeyError:
        raise KeyError("Zooniverse environment variables not set!")

    bot = ZooniBot(username=username, api_key=api_key)

    sincewhen = "2013-09-17"
    for t in find_zoonibot_tag(bot, sincewhen):
        print "Responding to %s with %s" % (t, zoonibot_response(t))
        # find_zoonibot_tag_since = lambda x : find_zoonibot_tag(x, sincewhen)
        # bot.find_and_respond(find_zoonibot_tag_since, zoonibot_response)

if __name__ == "__main__":
    main()
