#!/usr/bin/env python

import os

from zoonibot.bot import ZooniBot
from zoonibot.finders import find_gam_dor_hash
from zoonibot.responses import gammador_response

def main():
    try:
        username = os.environ["ZOONAME"]
        api_key = os.environ["ZOOKEY"]
    except KeyError:
        raise KeyError("Zooniverse environment variables not set!")
    
    bot = ZooniBot(username=username, api_key=api_key)

    sincewhen = "2013-09-17"
    for t in find_gam_dor_hash(bot, sincewhen):
        print "Responding to %s\n with %s\n" % (t, gammador_response(t))
        find_test_tags_since = lambda x : find_test_tags(x, sincewhen)
        bot.find_and_respond(find_gam_dor_hash, gammador_response)

if __name__ == "__main__":
    main()
