#!/usr/bin/env python

import os

from zoonibot.bot import ZooniBot
from zoonibot.responses import test_response
from zoonibot.finders import find_test_tags

def main():
    try:
        username = os.environ["ZOONAME"]
        api_key = os.environ["ZOOKEY"]
    except KeyError:
        raise KeyError("Zooniverse environment variables not set!")

    bot = ZooniBot(username=username, api_key=api_key)

    for t in find_test_tags(bot, since="2010-12-01"):
        print "Responding to %s with %s" % (t, test_response(t))
    	# bot.find_and_respond(find_test_tags, test_response)

if __name__ == "__main__":
    main()
