#!/usr/bin/env python

import os

from zoonibot.bot import ZooniBot
from zoonibot.responses import test_response
from zoonibot.finders import find_test_tags
from zoonibot.responses import help_response
from zoonibot.finders import find_help_tags

def main():
    try:
        username = os.environ["ZOONAME"]
        api_key = os.environ["ZOOKEY"]
    except KeyError:
        raise KeyError("Zooniverse environment variables not set!")
    
    bot = ZooniBot(username=username, api_key=api_key)

    sincewhen = "2013-09-17"
    for t in find_test_tags(bot, sincewhen):
        print "Responding to %s with %s" % (t, test_response(t))
        # find_test_tags_since = lambda x : find_test_tags(x, sincewhen)
        # bot.find_and_respond(find_test_tags_since, test_response)

if __name__ == "__main__":
    main()
