#!/usr/bin/env python

import os

from zoonibot.bot import ZooniBot
from zoonibot.responses import help_response
from zoonibot.finders import find_help_tags

def main():
    try:
        username = os.environ["ZOONAME"]
        api_key = os.environ["ZOOKEY"]
    except KeyError:
        raise KeyError("Zooniverse environment variables not set!")
        
    bot = ZooniBot(username=username, api_key=api_key)

    for t in find_help_tags(bot):
        print "Responding to %s with %s" % (t, help_response(t))
    bot.find_and_respond(find_help_tags, help_response)


if __name__ == "__main__":
    main()